let mode='Delivery';const cart=new Map(),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],money=n=>'$ '+n.toLocaleString('es-UY');
function renderCats(){$('#categories').innerHTML=DENEXA_DATA.categories.map(c=>`<button class="cat" data-cat="${c.name}"><img src="${c.img}" alt="${c.name}"><span>${c.name}</span></button>`).join('');$$('.cat').forEach(b=>b.onclick=()=>document.getElementById('group-'+slug(b.dataset.cat))?.scrollIntoView({behavior:'smooth',block:'start'}));}
const slug=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function productCard(p){return `<article class="product"><div class="prod-img"><img src="${p.img}" alt="${p.n}"></div><div class="prod-body"><h4>${p.n}</h4><p>${p.d}</p><div class="price">${money(p.p)}</div><div class="qty"><button data-m="${p.id}">−</button><span>${cart.get(p.id)||0}</span><button data-p="${p.id}">+</button></div></div></article>`}
function renderGroups(){$('#groups').innerHTML=DENEXA_DATA.categories.map(c=>{const list=DENEXA_DATA.products.filter(p=>p.c===c.name);if(!list.length)return'';return `<section class="group" id="group-${slug(c.name)}"><div class="group-head"><h3>${c.name}</h3><button data-up>VOLVER A CATEGORÍAS</button></div><div class="products">${list.map(productCard).join('')}</div></section>`}).join('');$$('[data-p]').forEach(b=>b.onclick=()=>changeQty(+b.dataset.p,1));$$('[data-m]').forEach(b=>b.onclick=()=>changeQty(+b.dataset.m,-1));$$('[data-up]').forEach(b=>b.onclick=()=>$('#categoriesSection').scrollIntoView({behavior:'smooth'}));}
function changeQty(id,d){const q=Math.max(0,(cart.get(id)||0)+d);q?cart.set(id,q):cart.delete(id);renderGroups();updateCartUi()}
function totals(){let count=0,total=0;cart.forEach((q,id)=>{const p=DENEXA_DATA.products.find(x=>x.id===id);count+=q;total+=q*p.p});return[count,total]}
function updateCartUi(){const[c,t]=totals();$('#cartBadge').textContent=c;$('#navBadge').textContent=c;$('#floatingCount').textContent=c;$('#floatingTotal').textContent=money(t);$('#floatingCart').classList.toggle('show',c>0)}
function openModal(id){$(id).classList.add('open');document.body.style.overflow='hidden'}function closeModals(){$$('.modal').forEach(m=>m.classList.remove('open'));document.body.style.overflow=''}
function renderCart(){let h='';cart.forEach((q,id)=>{const p=DENEXA_DATA.products.find(x=>x.id===id);h+=`<div class="cart-row"><div><b>${p.n}</b><p>${p.d}</p><strong>${money(p.p*q)}</strong></div><div class="controls"><button data-cm="${id}">−</button><b>${q}</b><button data-cp="${id}">+</button></div></div>`});$('#cartItems').innerHTML=h||'<p>Tu pedido está vacío.</p>';$('#cartTotal').textContent=money(totals()[1]);$$('[data-cp]').forEach(b=>b.onclick=()=>{changeQty(+b.dataset.cp,1);renderCart()});$$('[data-cm]').forEach(b=>b.onclick=()=>{changeQty(+b.dataset.cm,-1);renderCart()})}
function openCart(){renderCart();openModal('#cartModal')}$('#cartTop').onclick=openCart;$('#navCart').onclick=openCart;$('#floatingCart').onclick=openCart;$('#navHome').onclick=()=>scrollTo({top:0,behavior:'smooth'});$('#navCategories').onclick=()=>$('#categoriesSection').scrollIntoView({behavior:'smooth'});$('#promoJump').onclick=()=>document.getElementById('group-promo-del-dia').scrollIntoView({behavior:'smooth'});$$('.close').forEach(b=>b.onclick=closeModals);$$('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)closeModals()});$$('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;$$('[data-mode]').forEach(x=>x.classList.toggle('active',x.dataset.mode===mode))});$('#checkout').onclick=()=>{if(!cart.size)return;closeModals();openModal('#checkoutModal')};$$('[data-checkout-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.checkoutMode;$$('[data-checkout-mode]').forEach(x=>x.classList.toggle('active',x.dataset.checkoutMode===mode));$('#addressField').style.display=mode==='Delivery'?'block':'none'});$('#finish').onclick=()=>{if(!$('#name').value.trim())return alert('Escribí un nombre.');closeModals();openModal('#successModal')};$('#restart').onclick=()=>{cart.clear();updateCartUi();renderGroups();closeModals();scrollTo({top:0,behavior:'smooth'})};renderCats();renderGroups();updateCartUi();
