const categories=[{name:"Empanadas",icon:"🥟"},{name:"Bocatas",icon:"🥖"},{name:"Sándwiches",icon:"🥪"},{name:"Hamburguesas",icon:"🍔"},{name:"Papas y extras",icon:"🍟"},{name:"Bebidas",icon:"🥤"},{name:"Combos y promos",icon:"✦"},{name:"Ensaladas",icon:"🥗"},{name:"Salsas",icon:"🥣"},{name:"Postres",icon:"🍰"},{name:"Panes",icon:"🥐"},{name:"Especiales",icon:"⭐"}];
const products=[
{id:1,cat:"Empanadas",name:"Fugazzeta",desc:"Muzzarella y cebollas",price:80,icon:"🥟"},{id:2,cat:"Empanadas",name:"Aceitunas y queso",desc:"Aros de aceitunas y quesos",price:80,icon:"🥟"},{id:3,cat:"Empanadas",name:"Jamón y queso",desc:"Jamón en cubos y quesos",price:80,icon:"🥟"},{id:4,cat:"Empanadas",name:"Capresse",desc:"Quesos, tomate y albahaca",price:80,icon:"🥟"},{id:5,cat:"Empanadas",name:"Napolitana",desc:"Quesos, jamón, tomate y orégano",price:80,icon:"🥟"},{id:6,cat:"Empanadas",name:"Panceta y queso",desc:"Cubos de panceta y quesos",price:80,icon:"🥟"},{id:7,cat:"Empanadas",name:"Puerro y queso",desc:"Puerro, zanahorias y quesos",price:80,icon:"🥟"},{id:8,cat:"Empanadas",name:"Carne",desc:"Empanada de carne",price:80,icon:"🥟"},{id:9,cat:"Empanadas",name:"Carne dulce",desc:"Sabor tradicional",price:80,icon:"🥟"},{id:10,cat:"Empanadas",name:"Carne picante",desc:"Carne con un toque picante",price:80,icon:"🥟"},{id:11,cat:"Empanadas",name:"Pollo",desc:"Relleno de pollo",price:80,icon:"🥟"},{id:12,cat:"Empanadas",name:"Bondiola",desc:"Relleno de bondiola",price:80,icon:"🥟"},{id:13,cat:"Empanadas",name:"Desmenuzado",desc:"Sabor de carnes",price:80,icon:"🥟"},{id:14,cat:"Empanadas",name:"Empapancho",desc:"Especial de la casa",price:80,icon:"🥟"},{id:15,cat:"Empanadas",name:"Humita",desc:"Relleno de humita",price:80,icon:"🥟"},{id:16,cat:"Empanadas",name:"Primavera",desc:"Sabor primavera",price:80,icon:"🥟"},{id:17,cat:"Empanadas",name:"Espinaca",desc:"Relleno de espinaca",price:80,icon:"🥟"},{id:18,cat:"Empanadas",name:"Manzana",desc:"Empanada dulce",price:80,icon:"🥟"},{id:19,cat:"Empanadas",name:"Chocolate",desc:"Empanada dulce",price:80,icon:"🥟"},{id:20,cat:"Empanadas",name:"Membrillo",desc:"Empanada dulce",price:80,icon:"🥟"},
{id:21,cat:"Bocatas",name:"Bocata de jamón y queso",desc:"Queso muzzarella y jamón · pan artesanal de aprox. 15 cm",price:280,icon:"🥖"},{id:22,cat:"Bocatas",name:"Bocata de lomito y cheddar",desc:"Queso muzzarella, lomito y cheddar · pan artesanal",price:280,icon:"🥖"},{id:23,cat:"Bocatas",name:"Bocata de rúcula y cebolla",desc:"Muzzarella, lomito, tomate, cebolla y rúcula · pan artesanal",price:280,icon:"🥖"},
{id:24,cat:"Hamburguesas",name:"Hamburguesa clásica",desc:"Producto de muestra · reemplazaremos por el menú real",price:280,icon:"🍔"},{id:25,cat:"Hamburguesas",name:"Hamburguesa completa",desc:"Producto de muestra · reemplazaremos por el menú real",price:340,icon:"🍔"},{id:26,cat:"Sándwiches",name:"Sándwich caliente",desc:"Producto de muestra · reemplazaremos por el menú real",price:220,icon:"🥪"},{id:27,cat:"Papas y extras",name:"Papas fritas",desc:"Porción de muestra",price:150,icon:"🍟"},{id:28,cat:"Bebidas",name:"Refresco",desc:"Bebida de muestra",price:120,icon:"🥤"},{id:29,cat:"Combos y promos",name:"Combo Calentitas",desc:"Producto demostrativo para visualizar promociones",price:480,icon:"✦"},{id:30,cat:"Ensaladas",name:"Ensalada fresca",desc:"Producto de muestra",price:220,icon:"🥗"},{id:31,cat:"Salsas",name:"Salsa de la casa",desc:"Producto de muestra",price:60,icon:"🥣"},{id:32,cat:"Postres",name:"Postre del día",desc:"Producto de muestra",price:150,icon:"🍰"},{id:33,cat:"Panes",name:"Pan artesanal",desc:"Producto de muestra",price:120,icon:"🥐"},{id:34,cat:"Especiales",name:"Especial Calentitas",desc:"Producto de muestra",price:300,icon:"⭐"}];
const cart=new Map();let currentCategory=null,fulfillment="Delivery";const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],money=n=>"$ "+Number(n).toLocaleString("es-UY");
function renderCategories(){ $("#categories").innerHTML=categories.map(c=>`<button class="category-card ${currentCategory===c.name?"active":""}" data-category="${c.name}"><span class="category-icon">${c.icon}</span><span class="category-name">${c.name.toUpperCase()}</span></button>`).join(""); $$(".category-card").forEach(btn=>btn.onclick=()=>{currentCategory=btn.dataset.category;renderCategories();renderProducts();$("#catalogSection").scrollIntoView({behavior:"smooth",block:"start"})}); }
function visibleProducts(){ if(currentCategory)return products.filter(p=>p.cat===currentCategory); return [1,3,2,4,21,24].map(id=>products.find(p=>p.id===id)).filter(Boolean); }
function renderProducts(){const list=visibleProducts();$("#catalogTitle").textContent=currentCategory?currentCategory+" ✦":"Destacados ✦";$("#catalogEyebrow").textContent=currentCategory?"CATEGORÍA":"PARA EMPEZAR";$("#catalogMessage").textContent=currentCategory?`${list.length} productos en ${currentCategory}.`:"Elegí una categoría para ver sus productos, o mirá algunos destacados.";$("#products").innerHTML=list.map(p=>`<article class="product-card"><span class="product-category">${p.cat.toUpperCase()}</span><div class="product-art">${p.icon}</div><h4>${p.name}</h4><p>${p.desc}</p><div class="price">${money(p.price)}</div><div class="qty"><button data-minus="${p.id}">−</button><span>${cart.get(p.id)||0}</span><button data-plus="${p.id}">+</button></div></article>`).join("");$$('[data-plus]').forEach(b=>b.onclick=()=>changeQty(+b.dataset.plus,1));$$('[data-minus]').forEach(b=>b.onclick=()=>changeQty(+b.dataset.minus,-1));}
function changeQty(id,d){const q=Math.max(0,(cart.get(id)||0)+d);q?cart.set(id,q):cart.delete(id);renderProducts();updateCartButton()}
function totals(){let count=0,total=0;cart.forEach((q,id)=>{const p=products.find(x=>x.id===id);if(p){count+=q;total+=q*p.price}});return{count,total}}
function updateCartButton(){const{count,total}=totals();$("#badge").textContent=count;$("#floatingCount").textContent=count;$("#floatingTotal").textContent=money(total);$("#floatingCart").classList.toggle("show",count>0)}
function openModal(id){$(id).classList.add("open");$(id).setAttribute("aria-hidden","false");document.body.style.overflow="hidden"}function closeModals(){$$(".modal").forEach(m=>{m.classList.remove("open");m.setAttribute("aria-hidden","true")});document.body.style.overflow=""}
function renderCart(){let h="";cart.forEach((q,id)=>{const p=products.find(x=>x.id===id);h+=`<div class="cart-row"><div><strong>${p.name}</strong><p>${p.cat} · ${p.desc}</p><b>${money(p.price*q)}</b></div><div class="cart-row-controls"><button data-cart-minus="${id}">−</button><b>${q}</b><button data-cart-plus="${id}">+</button></div></div>`});$("#cartItems").innerHTML=h||"<p>Tu pedido está vacío.</p>";$("#cartTotal").textContent=money(totals().total);$$('[data-cart-plus]').forEach(b=>b.onclick=()=>{changeQty(+b.dataset.cartPlus,1);renderCart()});$$('[data-cart-minus]').forEach(b=>b.onclick=()=>{changeQty(+b.dataset.cartMinus,-1);renderCart()});}
function openCart(){renderCart();openModal("#cartModal")}function setFulfillment(m){fulfillment=m;$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));$$('[data-checkout-mode]').forEach(b=>b.classList.toggle('active',b.dataset.checkoutMode===m));$("#addressField").style.display=m==="Delivery"?"block":"none"}
$("#showCategories").onclick=$("#backToCategories").onclick=()=>$("#categoriesSection").scrollIntoView({behavior:"smooth"});$("#openCart").onclick=openCart;$("#floatingCart").onclick=openCart;$$('[data-mode]').forEach(b=>b.onclick=()=>setFulfillment(b.dataset.mode));$$('.close').forEach(b=>b.onclick=closeModals);$$('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)closeModals()});$("#checkoutButton").onclick=()=>{if(!cart.size)return;closeModals();setFulfillment(fulfillment);openModal("#checkoutModal")};$$('[data-checkout-mode]').forEach(b=>b.onclick=()=>setFulfillment(b.dataset.checkoutMode));$("#finishDemo").onclick=()=>{if(!$("#customerName").value.trim())return alert("Escribí un nombre para completar la simulación.");closeModals();openModal("#successModal")};$("#restartDemo").onclick=()=>{cart.clear();currentCategory=null;updateCartButton();renderCategories();renderProducts();closeModals();scrollTo({top:0,behavior:"smooth"})};
renderCategories();renderProducts();updateCartButton();setFulfillment("Delivery");
